[[OpenCVQt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf1028d2df992be32500a49699e0e2f2e47aa755"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "998d9911d5eda9962736450d6d3dbc6df405077b9b9b9516f93db16d7879c1b2"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.0+0/OpenCVQt.v0.6.0.aarch64-linux-gnu-cxx03.tar.gz"
[[OpenCVQt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96bf09dd8b1eb0ff483365464cf0431b2c5380af"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "232410c003fd154611d558558136f2f7241f2da41853c3df3bd2893af16b1216"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.0+0/OpenCVQt.v0.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenCVQt]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f62a2848de9d16e17167470f2db1eb6a43b91d34"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "847f19aa13bdb3e7c2fd5797f2b0ad511b99193edfcfb6f4767d828a40c59312"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.0+0/OpenCVQt.v0.6.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[OpenCVQt]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4f762bb3f92c49d35c5f6b65e90f2b169c1d295"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "5fc84d6d42336377dda17b60b57f78d4c29e3ec7b4ab4f62ecb11e54c2111245"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.0+0/OpenCVQt.v0.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "374685a6c03625a6d7c48f7dc42ec73a430b97af"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "44db5ad6a5529c0ae5740ae58990f6b8408c4201474adfd1e6a40c316eb3a516"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.0+0/OpenCVQt.v0.6.0.i686-linux-gnu-cxx03.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed5d7a4f2803398cc9a65a2dde483c7d121b93c6"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "cd3f5f79819dd0430558d47e45919bfb96f1349974334cce8108030059f6e70a"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.0+0/OpenCVQt.v0.6.0.i686-linux-gnu-cxx11.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f1bf29c8bec7b759f7a0e1e5bc2429cebe43dff"
os = "windows"

    [[OpenCVQt.download]]
    sha256 = "0f390c352a18c7258ebc3cd1a2834b406ecfe495fa6c063bb3042c851fe6c4ed"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.0+0/OpenCVQt.v0.6.0.i686-w64-mingw32-cxx03.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19620febc7cecf624f9d5cb2af3fe88aea707e1a"
os = "windows"

    [[OpenCVQt.download]]
    sha256 = "b097662e32d641fcfd97b0e8a60a63d61a257dea8c876b1595c7ae412efce77f"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.0+0/OpenCVQt.v0.6.0.i686-w64-mingw32-cxx11.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff04dffaba8b65880a89fdf698b4823c27aacc18"
os = "macos"

    [[OpenCVQt.download]]
    sha256 = "c34fd6b23c4ca42a5a6c28a78e1d10d689f39bbb658f13f6af0f19e10132bba8"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.0+0/OpenCVQt.v0.6.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5dd411da042075bdb5ec93b041ce4e2f35c9fce"
os = "macos"

    [[OpenCVQt.download]]
    sha256 = "3886ddc5afc7e0ba8a6490f872e2f7fc1ebef61668b009d53ee384c9ded56ac9"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.0+0/OpenCVQt.v0.6.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6cf796deed8cc1a445dadfea9b7d0422eaec323"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "02c0e91538ea59b3a3af992405e7e6e9750e02d6f02702b5481c0c8bb29cc9f7"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.0+0/OpenCVQt.v0.6.0.x86_64-linux-gnu-cxx03.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "443e614f348d28723bf9675acad47c645bf21a21"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "d692d2ba0701883490c2700cb688a1fbeb077488c48297a7657f80fcb0127acc"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.0+0/OpenCVQt.v0.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ebd7256e7f1605cb24f784d44e89611a8cfacca4"
os = "windows"

    [[OpenCVQt.download]]
    sha256 = "c96ef2a8cf02ddc0d260456ff01949b93bab04e3217952130673da833727fa17"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.0+0/OpenCVQt.v0.6.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9b97474a5f77e31435459703703cd23bb2a6e84"
os = "windows"

    [[OpenCVQt.download]]
    sha256 = "a43226756c01faaf122b9590f4fc9b7782d6fd823fb1f53896903931e09abbe0"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.0+0/OpenCVQt.v0.6.0.x86_64-w64-mingw32-cxx11.tar.gz"
