[[OpenCVQt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64428b3f244fe7fae7276890b604f4c34ca957a9"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "20675a157538fbc0111fb85fbde9a47dad1e46a3dde6ed6180edc7e840fb0a67"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.aarch64-linux-gnu-cxx03.tar.gz"
[[OpenCVQt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c894abda71da4eb221bfa3e27b360a5b12d5a28e"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "f915591cf4bd936285507fe2d5af049066a5f9811a132f1f359b1fda6724f35b"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenCVQt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bffbe5d46e6278fc3afef9f70a205bfc203f1d37"
libc = "musl"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "afb727f0bc2a97d347228811ebb2f99e60fb708f19fe1633dcf6352bbf81af95"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.aarch64-linux-musl-cxx03.tar.gz"
[[OpenCVQt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e61957ae67f71c0793d0b04e7688e0c975431073"
libc = "musl"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "5fe89296359a17262e2718c5ffaee9b0e80d198cac67ebfb54b7cf1b9eb5fc4d"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.aarch64-linux-musl-cxx11.tar.gz"
[[OpenCVQt]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0fd24f7eafce4362579890a80a18dba5bbb911e1"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "444abf18ff195750f3d6dc4b0f8301858351e1738a0b950ee8dd4f0dbb3475a7"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[OpenCVQt]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c72398262e93c2756f44eb5801bf45e6721b657"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "96810c910610077e55d7701ed867b19db3aaa4852b15e3391e2597231423a39c"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OpenCVQt]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2fafb19cbab8216fe8ede304ba1e6211b7dca913"
libc = "musl"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "caba29f4cd17f912e39c4cf6051c43550452270431567d7bf76d427cba0f6a18"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[OpenCVQt]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4f8719f6620ca7459e67666756fbc794c04c94f"
libc = "musl"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "dcc311cf58e9f62c7c5e790f70752ac7efe20630da6a18278ac96d88698b9c63"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5941fff84496e5960e417edbec2c2a4078bd0bcc"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "eea80dbba978bb56f17913da5999acb9825733845756e516b44e43d29e19ac2a"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.i686-linux-gnu-cxx03.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "140d093ab4d611dfb3bd7236ec0eaaf3a2733e0e"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "173b6ff3d54657c28034ae2fd37f5fb8c6c8ba22985ae0c81e29d2278e4a2f92"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.i686-linux-gnu-cxx11.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "160ffd8ad9f123181cc937e5b9c4a6044b638249"
libc = "musl"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "15881036b5d0bfc82adbafba568271aa18bf6018548c67d24eb45f9441e804bb"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.i686-linux-musl-cxx03.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "800e9511ac8e51638580f3790799bcfe1c25244c"
libc = "musl"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "7ee3c8ebdd8db2a888db284641569b5f91bfbb67d4c3b01a0c82a2ecc9245fb8"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.i686-linux-musl-cxx11.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e57583bb4cef0aede687ed4c13d8dd0a3823a0a0"
os = "windows"

    [[OpenCVQt.download]]
    sha256 = "b2225f05841e3b67cb0b3dbda1aa08b0b5ec63c8f94f85168a2eb8500f763f80"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.i686-w64-mingw32-cxx03.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dff26d9f8b9a602d2528c5351409c7a71290b8d1"
os = "windows"

    [[OpenCVQt.download]]
    sha256 = "258ea622289e067493d8400cec37ad71e18f06d648737f8daff22660c0cd212d"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.i686-w64-mingw32-cxx11.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdfb845c5b91da3967ea3e1079fdaf4fcef6dda7"
os = "macos"

    [[OpenCVQt.download]]
    sha256 = "922f0e0918a40daa921bee2ed5592c485c655e5d37a84ce4319d5784a34ea455"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c67ce1d663616de9a7132e8a215e9c11dfb85a0"
os = "macos"

    [[OpenCVQt.download]]
    sha256 = "a4a4c88849f47c44f9f30e08c7eea9c86334e3f2dded43354417d1f9fef87a9b"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67e2d67df40cba79be81c75e31bb75897e37f2f4"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "cd5f2ae2dd3ae971fae43b68f60586477473651629f65b1576553b4c0ac23abc"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.x86_64-linux-gnu-cxx03.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2144802d3a09281e9b26228b228edbd048c0e4dc"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "f9ab323d9e8db83842fff821e723bd39b7a70bfddc2ebda5c1d7ff05c932d688"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f4bef11a0651129484a3fbcd4e86bfc23f504f9"
os = "windows"

    [[OpenCVQt.download]]
    sha256 = "cb30f3eaea933496c90b0eea0f5c38024cda389a68a426f4bb0de1557496e181"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df477c6600fdfb6bf0b1daab707d87a6d64a3afc"
os = "windows"

    [[OpenCVQt.download]]
    sha256 = "07680e5b989798b3bbd1de4b9bb5f0a94ab48525f0cf7077a63d9d98d1c3b415"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.6.1+0/OpenCVQt.v0.6.1.x86_64-w64-mingw32-cxx11.tar.gz"
