[[OpenCVQt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3e890e449f223b2fd64e2bb6725fc32de70600a"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "e2b04a4787b6c36923cc017eaad3fc7de2cba9d5714b18767b3e4e876eae09e3"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.aarch64-linux-gnu-cxx03.tar.gz"
[[OpenCVQt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "216d3efe4821234e3be4fa6492f37c74335fa3e9"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "38f1a26fac68f21a6de0332462bf775e3f99b9715482aa0398846e9fb5b04a51"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenCVQt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0fa239ee832743187beffd320614d9af2746e063"
libc = "musl"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "7baf6bc5221c5ad3e41f69246dde80354d365b77393b99a63e9a76c6f8fd761a"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.aarch64-linux-musl-cxx03.tar.gz"
[[OpenCVQt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "723025426852d6f3bf3377c5b8b93de4d28ef0f0"
libc = "musl"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "0baa51ea15b18e373ac4126330be38d6e58707886397a4300ba495dd250f296e"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.aarch64-linux-musl-cxx11.tar.gz"
[[OpenCVQt]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5461c121fece903a5eb17153792184b3cf87b1f0"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "97e86ff8cb0ea1c78174bf53de89c70a822cdc78a0dbdadde774455acf7b8483"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[OpenCVQt]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "246b84820c44ae8aa30476a3d20e6e5d783c2e8b"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "08011909acd2ed3ab9fac91e7c29b670e27722b116f6aa32b89dc072ad7903be"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OpenCVQt]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7ce39173df30646c283cf40910df5140dba0aba"
libc = "musl"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "39a4e22713d93ffe83f3f8e69435006a6b0d4e40d439c96eee69c684845e3d2d"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[OpenCVQt]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7548d1b484a1b5b2a2c6a706de4f018f709b7b88"
libc = "musl"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "3f738c93f8446a2e278750a4a324da4fc3daf7216ad2a8675d55c8d9110ead1e"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ed45e7b5172dc0fa3a9e76cd14e09170a36c8ed"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "b25da877841ce0e5ed80ba83d4208b45890c1ca01f0a23e7f740b592026d75be"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.i686-linux-gnu-cxx03.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfc7a5e6a1c2e70c8ec9ce9661d795fc366454d4"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "07a183a890be166dc03375519d2c83d915fde3c50bb89d123b69ba530c60562a"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.i686-linux-gnu-cxx11.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02d0f980b1732ad308bd11d236e3b65e3595b37d"
libc = "musl"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "3aa5899bd2d750b2c1cbb2ccdafe0457d354ad70da95aac691726cb028f58945"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.i686-linux-musl-cxx03.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37e197aa35eacd8f07abc9eb441f37516cb38db7"
libc = "musl"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "c60db977942e4498052673703d6fdecf941da4b550c14aabdc2c0864be42980d"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.i686-linux-musl-cxx11.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "153ec17c825b1b2cdcd9e782744c1ab5b8f672d8"
os = "windows"

    [[OpenCVQt.download]]
    sha256 = "971812c562cf4b876821966bd460ca56d9e4d746506e1a332bdb648cf98b346e"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.i686-w64-mingw32-cxx03.tar.gz"
[[OpenCVQt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b5c1fc142d7e90e19f53fbe2123eac241bcca7e"
os = "windows"

    [[OpenCVQt.download]]
    sha256 = "a8d4f9660fa037854852a7c9a876282f7ffe74dc4a74e37caa8112b77d5c3d65"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.i686-w64-mingw32-cxx11.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65268f095d3f32c53917e047caf6bf02e77a32f4"
os = "macos"

    [[OpenCVQt.download]]
    sha256 = "c5cdaedd3550ad3984a1c618717eb6c174abcad798d742221f415410d52d1d25"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50ddda43d2d8a9f834fbf4392d1fa2f58854414c"
os = "macos"

    [[OpenCVQt.download]]
    sha256 = "43e153e3f70c398510642e2ab1a707ca739c632418625ddd6fdccac5c35d0d36"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b45d4677377bac9f8120a41962955254c72374bf"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "917ca9604f0e502ee7b51dcb2643768e1764121dee98cc83d8dd4be2393ae53f"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.x86_64-linux-gnu-cxx03.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "141fd9328b57d52016220a622a530eb06ffc1d24"
libc = "glibc"
os = "linux"

    [[OpenCVQt.download]]
    sha256 = "fefe4527b2021496272d3726a5571993f223b1580bd880044a05cb8bd353ef7d"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23eeaa6cc1894b2907d0a40e641986fabc43e077"
os = "windows"

    [[OpenCVQt.download]]
    sha256 = "e6041c042eff6f6062448d3c9a2ada53989cf7427904647ac68ec4fc23426c72"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[OpenCVQt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25e128efc0761cb308627d32e0a6e749cf1c0a3b"
os = "windows"

    [[OpenCVQt.download]]
    sha256 = "862029e2a7b4f47055109de01bd189d0ddc6bc69a395f7186ea436d38a152341"
    url = "https://github.com/terasakisatoshi/OpenCVQt_jll.jl/releases/download/OpenCVQt-v0.7.1+0/OpenCVQt.v0.7.1.x86_64-w64-mingw32-cxx11.tar.gz"
